// The vault's trade corridors, laid onto a map as Azgaar journeys.
//
// This lives on its own because two scripts need it: `build.js`, which lays the
// corridors on a map it has just generated, and `modernize.js`, which lays them
// on a map generated by an older version that had no journeys at all. One copy,
// because a corridor drawn two subtly different ways on two maps is exactly the
// kind of drift the vault's own sync scripts exist to prevent.
//
// `layJourneys` runs INSIDE the page, so it may only touch Azgaar's globals and
// the plain object it is handed. build.js runs it inside a larger evaluate by
// injecting its source; modernize.js hands it straight to page.evaluate.
const fs = require('fs');

// What a corridor's "Carried by" column means on the ground. Azgaar ships
// twenty transport types and none of them is a freight caravan, so three are
// added: a corridor that moves salt on camels should say camels rather than
// borrow a stagecoach. The domain is what actually matters — it decides
// whether a leg is routed over the roads or over the sea.
const CARRIER = {
  sea:     { name: 'Sailing Ship', domain: 'water' },
  river:   { name: 'River barge',  domain: 'water' },
  road:    { name: 'Freight wagon', domain: 'land' },
  caravan: { name: 'Camel caravan', domain: 'land' },
};
const EXTRA_TRANSPORTS = [
  { name: 'Freight wagon', speed: 4, domain: 'land',  hoursPerDay: 10 },
  { name: 'Camel caravan', speed: 4, domain: 'land',  hoursPerDay: 10 },
  { name: 'River barge',   speed: 5, domain: 'water', hoursPerDay: 10 },
];
// The nine corridor colours the site already uses, in the note's own row
// order, so a corridor is the same colour on the map as in the web view.
const ROUTE_COLORS = ['#1f5f8b', '#8a5a1f', '#2f6b46', '#7a2f5f', '#5a4a9a',
                      '#146b6b', '#9a3b26', '#4a5f22', '#6b4a2f'];

// The nine trade corridors, read out of the note that already describes them.
// Same rule as the diplomacy: the markdown table is the source of truth and
// nothing here restates it. A row is
//   | **Name** | Road | [[A]] -> [[B]] -> [[C]] | what it carries |
// and the run is an ordered list of wikilinks, exactly as the site's own
// `view: routes` reads it — so a stop added to the note moves the line on the
// map and on the site together, with no change here.
function readCorridors() {
  const p = '/home/user/Towers-of-Saeroth/campaign/world/Trade Routes.md';
  const out = [];
  for (const line of fs.readFileSync(p, 'utf8').split('\n')) {
    const t = line.trim();
    if (t[0] !== '|') continue;
    const cs = t.replace(/^\|/, '').replace(/\|$/, '').split('|').map(c => c.trim());
    if (cs.length < 4) continue;
    const name = cs[0].replace(/\*+/g, '').trim();
    const carry = cs[1].replace(/\*+/g, '').trim().toLowerCase();
    const stops = [...cs[2].matchAll(/\[\[([^\]|#]+)[^\]]*\]\]/g)].map(m => m[1].trim());
    if (!name || stops.length < 2 || !CARRIER[carry]) continue;
    out.push({ name, carry, stops, cargo: cs[3] || '' });
  }
  return out;
}

// Everything below this line executes in the browser.
function layJourneys(a) {
  // Nation name -> state id. build.js has this already from its naming pass;
  // modernize.js is looking at a map somebody else named, so both the vault's
  // full name and whatever short form the map carries have to match.
  const cc = pack.cells;
  const byName = {};
  for (const s of pack.states) {
    if (!s || !s.i || s.removed) continue;
    if (s.fullName) byName[s.fullName] = s.i;
    if (s.name) byName[s.name] = s.i;
  }
// ---- the vault's trade corridors, drawn as journeys -------------------
// Trade is Azgaar's own feature now: a journey is a named, multi-leg route
// with a transport per leg, saved with the map and drawn on its own layer.
// The nine corridors the notes describe are exactly that shape, so they go
// on the map as journeys rather than as decoration — each leg pathfound
// between two real settlements over the real roads or the real sea lanes,
// which is also the check that the corridor is possible on this map at
// all: a leg with no route means two nations the vault has trading are
// not actually connected.
const trade = { laid: [], partial: [], legs: 0, skipped: [], detour: [], rerouted: [] };
try {
  const tlist = Transports.getDefaults();
  let tid = Math.max.apply(null, tlist.map(t => t.i)) + 1;
  for (const t of a.EXTRA_TRANSPORTS) tlist.push(Object.assign({ i: tid++ }, t));
  Transports.set(tlist);

  // Azgaar's sea router prices water by how far from shore it is —
  // coastline 1, sea 1.8, open sea 4, ocean 6, anything deeper 8 — because
  // its own searoutes are coasting trade between neighbouring ports. Every
  // corridor here came out of that traced along the shoreline, so a run
  // from Xian Ti to Nordheim was drawn as an outline of the coast rather
  // than as a sea lane, and looked like one.
  //
  // Replace the schedule for the length of this pass. The cheapest water
  // is now `sea` — a cell or two off the beach, where a hull with a
  // destination actually sails — the shoreline itself costs more than
  // that, and the deep ocean is a premium rather than a wall.
  //
  // Keep a gradient. Flattening the schedule outright (everything at 1.6)
  // leaves the search nothing to follow, so it fans across the whole ocean
  // hunting one port's haven and the build goes from half a minute to ten.
  // The hard rules are untouched: leaving through a cell's own haven,
  // staying on a navigable river and not sailing into ice all come back
  // from the original as Infinity and are passed straight through.
  // The schedule runs the other way from Azgaar's: the shore is the
  // expensive water and the open ocean the cheap one, so a corridor
  // crosses instead of creeping. Making `sea` the cheapest tier was not
  // enough — a route still traced the coast one cell out, which looks
  // exactly as much like an outline of the continent as tracing the beach
  // does. There is still a gradient, and it still points somewhere: flat
  // water leaves the search nothing to follow, so it fans out across the
  // whole ocean hunting one port's haven and the build takes ten minutes.
  // Two schedules, because a barge and a merchantman want opposite things.
  // `sea` makes the open ocean the cheap water so a hull crosses instead of
  // creeping; `river` inverts it, so a barge takes a river where one goes
  // its way.
  //
  // It does not make one where there is none. The router refuses any land
  // cell that is not a recorded navigable river edge, so re-pricing can
  // only choose between paths that already exist — the Delta Run still
  // runs four times its straight line, because Grauthaven and Ilmen Wharf
  // are on different drainages and the only way between them is out to sea
  // and round. That is the map telling the truth, not the router failing.
  const WATER_MOD = {
    sea:   { land: 1.0, '-1': 1.9, '-2': 1.35, '-3': 1.05, '-4': 1.0, deep: 1.0 },
    river: { land: 0.7, '-1': 1.1, '-2': 1.8, '-3': 2.6, '-4': 3.2, deep: 3.6 },
  };
  let mod = WATER_MOD.sea;
  const seaCost = Routes.getWaterPathCost.bind(Routes);
  Routes.getWaterPathCost = function (from, to) {
    const c = seaCost(from, to);
    if (!isFinite(c)) return c;
    const d2 = dist2(pack.cells.p[from], pack.cells.p[to]);
    if (!(d2 > 0)) return c;
    const t2 = pack.cells.t[to];
    return d2 * (t2 >= 0 ? mod.land : (mod[t2] === undefined ? mod.deep : mod[t2]));
  };

  const burgsOf = id => pack.burgs.filter(b => b && b.i && !b.removed && b.state === id);
  const capitalOf = id => {
    const st = pack.states[id];
    return (st && st.capital && pack.burgs[st.capital]) || null;
  };
  // Where a corridor touches a nation. The capital wins whenever it CAN —
  // a delta or river capital is a valid water endpoint and the sea router
  // will run a hull up the river to reach it, which is the difference
  // between a corridor that visits a country and one that skims past its
  // beach. Only a capital the water cannot reach hands the leg to a port.
  //
  // Ranked rather than picked, because a valid endpoint is not the same as
  // a reachable one — the sea router insists on leaving through a cell's
  // own haven — so the leg tries the next candidate instead of giving up.
  const endpointsOf = (id, domain) => {
    const cap = capitalOf(id);
    const score = b => {
      let v = 1 + (b.population || 0);
      if (domain === 'water' && b.port) v *= 4;
      if (b === cap) v *= 40;
      return v;
    };
    return burgsOf(id)
      .filter(b => Journeys.isValidEndpoint(b.cell, domain))
      .sort((x, y) => score(y) - score(x))
      .slice(0, 3);
  };

  const journeys = [];
  a.corridors.forEach((cor, ci) => {
    const car = a.CARRIER[cor.carry];
    const tr = Transports.get(car.name);
    mod = WATER_MOD[cor.carry] || WATER_MOD.sea;
    const segments = [];
    let firstEnd = null, lastEnd = null;
    for (let k = 0; k + 1 < cor.stops.length; k++) {
      const na = cor.stops[k], nb = cor.stops[k + 1];
      const ia = byName[na], ib = byName[nb];
      if (!ia || !ib) { trade.skipped.push(`${cor.name}: ${na}/${nb} not on the map`); continue; }
      const AS = endpointsOf(ia, car.domain), BS = endpointsOf(ib, car.domain);
      let A = null, B = null, r = null, why = 'nowhere to leave from';
      for (const x of AS) {
        for (const y of BS) {
          // a land leg between two landmasses can only fail, and failing
          // costs a Dijkstra over the whole pack: nine of those per leg
          // turned a half-minute build into five minutes
          if (car.domain === 'land' && cc.f[x.cell] !== cc.f[y.cell]) {
            why = 'no-land-path'; continue;
          }
          const t2 = Journeys.findPath(x.cell, y.cell, car.domain);
          if (t2.errorCode || t2.points.length < 2) { why = t2.errorCode || 'no path'; continue; }
          A = x; B = y; r = t2; break;
        }
        if (r) break;
      }
      // A leg its own carrier cannot make is not automatically a hole in
      // the world: if the barges cannot float between two fens because
      // they sit on different drainages, the cargo goes overland, which is
      // what a smuggling run does anyway. Try the other domain before
      // calling the corridor broken — and say which legs did it, because a
      // river route carried on wheels is worth knowing about.
      let usedTr = tr;
      if (!r) {
        const alt = car.domain === 'water' ? 'land' : 'water';
        const altTr = Transports.get(alt === 'land' ? a.CARRIER.road.name
                                                    : a.CARRIER.sea.name);
        const AS2 = endpointsOf(ia, alt), BS2 = endpointsOf(ib, alt);
        for (const x of AS2) {
          for (const y of BS2) {
            if (alt === 'land' && cc.f[x.cell] !== cc.f[y.cell]) continue;
            const t3 = Journeys.findPath(x.cell, y.cell, alt);
            if (t3.errorCode || t3.points.length < 2) continue;
            A = x; B = y; r = t3; usedTr = altTr; break;
          }
          if (r) break;
        }
        if (r) trade.rerouted.push(`${cor.name}: ${na} \u2192 ${nb} goes by ` +
                                   `${usedTr.name.toLowerCase()} (${why})`);
      }
      if (!r) { trade.skipped.push(`${cor.name}: ${na} \u2192 ${nb} (${why})`); continue; }
      if (!firstEnd) firstEnd = A;
      lastEnd = B;
      segments.push({ i: segments.length, name: `${A.name} \u2192 ${B.name}`,
                      from: A.cell, to: B.cell, transport: usedTr.name, speed: usedTr.speed,
                      distance: r.distance, points: r.points });
    }
    const carried = segments.length;
    // A sea corridor that begins and ends at a wharf never enters the
    // country it is named for — it skims the beach and leaves, which is
    // what made the lines look like an outline of the coast rather than a
    // trade route. Where the capital could not take the hull itself, walk
    // the last stretch: the road from the quay up to the city is part of
    // the run, and mixed transport is what the Journeys layer is for.
    if (car.domain === 'water' && segments.length) {
      const road = Transports.get(a.CARRIER.road.name);
      const spur = (fromB, toB) => {
        if (!fromB || !toB || fromB === toB) return null;
        if (cc.f[fromB.cell] !== cc.f[toB.cell]) return null;
        const r2 = Journeys.findPath(fromB.cell, toB.cell, 'land');
        if (r2.errorCode || r2.points.length < 2) return null;
        return { name: `${fromB.name} \u2192 ${toB.name}`, from: fromB.cell, to: toB.cell,
                 transport: road.name, speed: road.speed,
                 distance: r2.distance, points: r2.points };
      };
      const head = spur(capitalOf(byName[cor.stops[0]]), firstEnd);
      const tail = spur(lastEnd, capitalOf(byName[cor.stops[cor.stops.length - 1]]));
      if (head) segments.unshift(head);
      if (tail) segments.push(tail);
      segments.forEach((sg, k2) => { sg.i = k2; });
    }
    // How far a leg wanders against the straight line between its ends.
    // A sea lane that creeps round every bay instead of crossing scores 3
    // or 4 here and reads on the map as an outline of the coast, which is
    // not something any number in the build was measuring.
    for (const sg of segments) {
      const A2 = cc.p[sg.from], B2 = cc.p[sg.to];
      const straight = Math.hypot(A2[0] - B2[0], A2[1] - B2[1]);
      if (straight > 1) trade.detour.push([cor.name, sg.name, sg.distance / straight]);
    }
    if (carried === cor.stops.length - 1) trade.laid.push(cor.name);
    else trade.partial.push(`${cor.name} ${carried}/${cor.stops.length - 1} legs`);
    if (!segments.length) return;
    journeys.push({ i: journeys.length, name: cor.name, type: 'Trade route',
                    color: a.ROUTE_COLORS[ci % a.ROUTE_COLORS.length], segments, lock: true });
    trade.legs += carried;
  });
  Routes.getWaterPathCost = seaCost;   // the app's own routes keep coasting
  // replaces the one journey the generator seeds every map with
  pack.journeys = journeys;
  // Azgaar's default styles are sized for a canvas about a thousand pixels
  // across. This one is 3,600, so a 1.8px corridor is a hairline you
  // cannot see at fit-width — which rather defeats putting the trade on
  // the map. Widen the journey stroke to match the canvas.
  // The style record is the source of truth since 1.150, but writing to it
  // does not touch the drawing: `Styles.apply` is what pushes the attrs
  // onto the layer group. Set one and not the other and the saved map is
  // right while every render out of this build is a hairline.
  if (window.styles && styles.journeys) {
    styles.journeys.attrs['stroke-width'] = a.journeyStroke || 5;
    styles.journeys.attrs.opacity = 0.85;
    try { Styles.apply('journeys'); } catch (e) { /* older build */ }
  }
} catch (e) { trade.skipped.push('trade: ' + e.message); }
  return trade;
}

module.exports = { CARRIER, EXTRA_TRANSPORTS, ROUTE_COLORS, readCorridors, layJourneys };
