"""Regional SVG backgrounds: original terrain colors, crisp vector geography.

Tile dimensions advertise 4x sampling; small detail grain is generated by SVG.
Existing overview images and authoritative geography are not modified.
"""
from pathlib import Path
import base64, io, re, copy, json, xml.etree.ElementTree as E
from PIL import Image
R=Path(__file__).resolve().parent.parent;O=R/'site/atlas'
A=O/'assets/zoom-tiles';A.mkdir(exist_ok=True)
NS='http://www.w3.org/2000/svg';XL='http://www.w3.org/1999/xlink'
E.register_namespace('',NS);E.register_namespace('xlink',XL)
W,H,TW,TH=3840,2160,480,270
def bounds(d):
 n=list(map(float,re.findall(r'-?\d+(?:\.\d+)?',d)))
 return (min(n[::2]),min(n[1::2]),max(n[::2]),max(n[1::2])) if len(n)>3 else None
def overlaps(b,x,y):return b and b[0]<=x+TW+8 and b[2]>=x-8 and b[1]<=y+TH+8 and b[3]>=y-8
for mode in ['terrain','political']:
 root=E.parse(R/'atlas-source'/(mode+'-unlabelled.svg')).getroot()
 raster=Image.new('RGBA',(W,H));vectors=[]
 for e in root:
  if e.tag.endswith('image'):
   url=e.get('href') or e.get('{'+XL+'}href');im=Image.open(io.BytesIO(base64.b64decode(url.split(',',1)[1]))).convert('RGBA')
   if float(e.get('opacity','1'))!=1:im.putalpha(im.getchannel('A').point(lambda a:a*float(e.get('opacity','1'))))
   raster.alpha_composite(im)
  elif e.tag.endswith('g'):
   entries=[]
   for child in e:
    if child.tag.endswith('path'):
     b=bounds(child.get('d',''));entries.append((child,b))
   vectors.append((e,entries))
  elif e.tag.endswith('path'):
   # Split disconnected outlines, so distant shores do not inflate every tile.
   entries=[]
   for subpath in re.findall(r'M[^M]+',e.get('d','')):
    p=copy.deepcopy(e);p.set('d',subpath)
    width=float(p.get('stroke-width','1'));p.set('stroke-width',str(width*.65))
    entries.append((p,bounds(subpath)))
   vectors.append((None,entries))
 for row in range(8):
  for col in range(8):
   x,y=col*TW,row*TH
   tile=E.Element('{'+NS+'}svg',{'width':str(TW*4),'height':str(TH*4),'viewBox':f'{x} {y} {TW} {TH}'})
   buf=io.BytesIO();raster.crop((x,y,x+TW,y+TH)).convert('RGB').save(buf,format='PNG')
   E.SubElement(tile,'{'+NS+'}image',{'x':str(x),'y':str(y),'width':str(TW),'height':str(TH),'{'+XL+'}href':'data:image/png;base64,'+base64.b64encode(buf.getvalue()).decode()})
   defs=E.SubElement(tile,'{'+NS+'}defs')
   f=E.SubElement(defs,'{'+NS+'}filter',{'id':'grain','x':str(x),'y':str(y),'width':str(TW),'height':str(TH),'filterUnits':'userSpaceOnUse','color-interpolation-filters':'sRGB'})
   E.SubElement(f,'{'+NS+'}feTurbulence',{'type':'fractalNoise','baseFrequency':'1.1','numOctaves':'2','seed':'23','stitchTiles':'stitch'})
   E.SubElement(f,'{'+NS+'}feColorMatrix',{'type':'saturate','values':'0'})
   E.SubElement(tile,'{'+NS+'}rect',{'x':str(x),'y':str(y),'width':str(TW),'height':str(TH),'fill':'#605e4a','filter':'url(#grain)','opacity':'.065'})
   for group,entries in vectors:
    matched=[p for p,b in entries if overlaps(b,x,y)]
    if not matched:continue
    parent=E.SubElement(tile,'{'+NS+'}g',dict(group.attrib)) if group is not None else tile
    for p in matched:
     child=copy.deepcopy(p)
     if group is not None and group.get('stroke')=='#6da8b4':child.set('stroke-width',str(float(child.get('stroke-width','1'))*.7))
     parent.append(child)
   E.ElementTree(tile).write(A/f'{mode}-{col}-{row}.svg',encoding='utf-8',xml_declaration=True)
sizes=[p.stat().st_size for p in A.glob('*.svg')]
(A/'manifest.json').write_text(json.dumps({'tileWidth':TW,'tileHeight':TH,'columns':8,'rows':8,'sampling':4,'count':len(sizes),'totalBytes':sum(sizes),'maxTileBytes':max(sizes)},indent=2))
print(f'{len(sizes)} regional SVG tiles; {sum(sizes)/1024/1024:.1f} MiB total; largest {max(sizes)//1024} KiB.')
