// Build the two things the relations web needs to sit on top of the world map:
//
//   site/map/saeroth-political.png   the map itself, with no labels on it —
//                                    the overlay draws its own
//   site/nation-positions.json       where each nation is, so a node can be
//                                    pinned to its own country
//
// Both are DERIVED from campaign/Saeroth.map, so rerun this after any rebuild
// of the map and the overlay follows it. Nothing here is hand-placed.
//
//   node tools/map_backdrop.js
//   python3 tools/shrink_backdrop.py     # then squeeze the PNG down for the PWA
//
// Positions come from each state's `pole` — Azgaar's pole of inaccessibility,
// the point it puts a country's own label at, which is the deepest interior
// point rather than the centroid. For a crescent-shaped nation the centroid can
// land in the sea; the pole cannot.
//
// Needs Azgaar served on 5199, the same as build.js.
const APP = require('./mapgen/app.js');
const fs = require('fs');
const path = require('path');

const MAP = process.env.MAP || 'campaign/Saeroth.map';
const PNG = process.env.PNG || 'site/map/saeroth-political.png';
const JSON_OUT = process.env.JSON_OUT || 'site/nation-positions.json';

(async () => {
  const b = await APP.launch();
  // the app must be told the saved map's own canvas size or it loads it zoomed
  const p = await APP.openApp(b, { width: 3600, height: 2150, cells: 1000,
                                   viewport: { width: 3600, height: 2150 } });
  await APP.loadMap(p, MAP);

  // states filled, relief for texture, and NOTHING that writes text: the
  // overlay puts a name under every node and two sets of labels is a mess.
  // The trade journeys are off for the same reason — the overlay draws the
  // corridors itself, from the note.
  await APP.setLayers(p, ['texture', 'lakes', 'rivers', 'relief', 'states', 'borders', 'ice']);
  // the app's own chrome sits over the corners of the canvas: the options
  // handle top-left and the menu handle bottom-right both land in the
  // screenshot as little arrow buttons floating in the ocean
  await APP.hideChrome(p);
  await p.waitForTimeout(2500);

  fs.mkdirSync(path.dirname(PNG), { recursive: true });
  await APP.shoot(p, PNG);
  console.log('wrote ' + PNG);

  const data = await p.evaluate(() => ({
    width: graphWidth, height: graphHeight,
    nations: Object.fromEntries(pack.states
      .filter((s) => s.i && !s.removed && s.pole)
      .map((s) => [s.fullName, [Math.round(s.pole[0]), Math.round(s.pole[1])]])),
  }));
  data.image = 'map/' + path.basename(PNG);
  data.note = 'Generated by tools/map_backdrop.js from campaign/Saeroth.map — do not hand-edit.';
  fs.writeFileSync(JSON_OUT, JSON.stringify(data, null, 1) + '\n');
  console.log(`wrote ${JSON_OUT} — ${Object.keys(data.nations).length} nations on ${data.width}x${data.height}`);
  await b.close();
})();
